### ISSUE TITLE
Window / dialog has a different theme then other windows

### ISSUE THREAD

**Issue by Appeltabak** [elementary/screenshot-tool#20]
In elementary OS, the window / dialog of the screenshot tool has a dark theme that's different from other windows (like Calender and Photos). Is there a specific reason why only this app's window has a different theme? I think it is inconsistent with the default theme of elementary OS.

I'm willing to submit a PR that removes the dark theme preference if that's appreciated.

**Comment by cassidyjames** [comment]
I think the idea is that dark apps are less distracting from the content (which you're about to screenshot when using this tool). However, I'm not certain that rationale cleanly applies to this app, and I'm open to input from @elementary/ux.

**Comment by danrabbit** [comment]
Screenshots of what it looks like in white:

![screenshot from 2018-05-04 11 17 18 2x](https://user-images.githubusercontent.com/7277719/39645325-cb8a0840-4f8c-11e8-895a-eddafa9bedea.png)
![screenshot from 2018-05-04 11 17 30 2x](https://user-images.githubusercontent.com/7277719/39645326-cbadd50e-4f8c-11e8-8610-ed47c254350d.png)

**Comment by jlnr** [comment]
> the window / dialog of the screenshot tool has a dark theme that's different from other windows (like Calender and Photos)

[New versions of Photos always use the dark theme](https://github.com/elementary/photos/pull/284), just like Screenshot Tool. I think it makes sense for Screenshot Tool to be consistent with Photos (= it should keep the dark theme).

**Comment by danrabbit** [comment]
Yeah I think there's good arguments on both sides here. On the one hand this is a media application but on the other hand it's a transient utility with a short, linear workflow so it makes sense to keep with the white, flat style for that. I personally think either one could work at this point and I'm not terribly hung up about it if a significant amount of people have strong feelings one way or the other
