### ISSUE TITLE
appdata file generation/installation broken since 0.1.3 Release

### ISSUE THREAD

**Issue by decathorpe** [elementary/screenshot-tool#21]
I don't understand why, but the "Release 0.1.3" commit / rev. 324 in bzr broke appdata generation (only an empty file is installed to the destination). The error is the same with the .tar.gz release tarball on github, the .tar.xz file on launchpad and a bzr snapshot of rev324.

**Comment by codygarver** [comment]
Fixed in c745581b2af74bd663cd7e5a109309dbd8eb9dfd

**Comment by decathorpe** [comment]
Thanks :+1:
