### ISSUE TITLE
Save folder when screenshot key is pressed

### ISSUE THREAD

**Issue by jansaputra** [elementary/screenshot-tool#25]
At the moment, when I'm pressing the "print screen" key, the resulting screenshot is saved in my ~/Pictures folder instead of the folder specified in the "folder-dir" setting. If I'm calling the screenshot-tool from the command line using "screenshot-tool -s", the picture is saved as expected in the "folder-dir".

I am wondering which command is triggered when the print screen key is pressed? Having a hard time figuring that out somehow. Also I'm wondering if this is intended behavior? If not, and if I know the exact command which is triggered by the print screen key, I might be able to fix it.

**Comment by danrabbit** [comment]
When you press the screenshot key, this is actually coming from [Gala](https://code.launchpad.net/gala) instead of screenshot tool.

**Comment by jansaputra** [comment]
Interesting, thank you for this info! So this means gala itself has its own integrated screenshot tool? The naming of the files (and also the behavior with the sound that is played) seems to be (almost) identical. Might be probably nice to join both and just use the screenshot-tool? :)

**Comment by danrabbit** [comment]
Actually the other way around. Eventually we need screenshot tool to use Gala to retrieve the screenshot because on Wayland it won't have permission to see the other windows
