### ISSUE TITLE
Taking a screenshot using PrtScr button gives no visual feedback.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/screenshot-tool#30]
Right now, hitting PrtScr does take the screenshot and save it, but it gives absolutely no visual feedback whatsoever that the job has been done. Ubuntu Unity has a nice snapshot like animation showing the user that a screenshot is taken.

This is sometimes even more valuable when one wants to take screenshots at an exact moment, say during an animated GIF/video or any similar use case.

**Comment by uncertainquark** [comment]
Can there be a notification instead of a visual snapshot animation. That would do too.

**Comment by basiern** [comment]
A notification would be great

**Comment by suprko** [comment]
Agree

**Comment by ragerin** [comment]
A notification would surely suffice, but I think for the completeness and keeping with eOS philosophy, an animation would be the best solution. I think a flashing white line around the entire screen and an appropriate sound effect would be a good visual and audible feedback.

**Comment by WilsenHernandez** [comment]
Agree, an animation like what Windows 10 does when you Super+PrtScr would be enough

**Comment by samosaara** [comment]
AFAIK, a notification would be the easiest way, not the most glamorous though, a flash like GNOME's would be very easy too and a little bit fancier...

**Comment by srseven** [comment]
Agree.

**Comment by danrabbit** [comment]
Please don't make "me too" or "agree" comments. Use reactions. This keeps comments from becoming cluttered

**Comment by cassidyjames** [comment]
I'm in favor of a notification; keep in mind that a notification could theoretically let you open the screenshot when clicked if it had an action specified.

**Comment by artemanufrij** [comment]
@cassidyjames what is the goal? to run schreenshot-tool on click "print"-key? currently gala saves screenshots on click "print"-key…

**Comment by danrabbit** [comment]
Since Gala is responsible for taking screenshots on keypress, this issue is invalid for screenshot tool. I've opened an issue against Gala for this feature request.
