### ISSUE TITLE
weird behavior when cancelling drawing the "area rectangle" with "Esc" key

### ISSUE THREAD

**Issue by decathorpe** [elementary/screenshot-tool#35]
When doing an "area" type screenshot, start selecting a rectangle with the mouse, and then press the "Esc" key to abort. This leads to an "invisible" (or empty) application window (tested on elementaryOS stable and on fedora 25).

**Comment by purejava** [comment]
The opacity of `ScreenshotWindow` stays on 0 when this happens.
Usually, on taking an area screenshot without pressing ESC, the opacity is set to 1 again here on [line 224](https://github.com/elementary/screenshot-tool/blob/master/src/ScreenshotWindow.vala#224).

On pressing ESC, line 224 of the code never gets hit.
