### ISSUE TITLE
`screenshot-tool -r` shortcut does not show 'Save' dialog

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/screenshot-tool#36]
Taking a screenshot of an area of the screen with `screenshot-tool -r` used to present you with the Save dialog after taking the screenshot. It does not anymore. Is this by design?

**Comment by Gabriel-p** [comment]
I guess this is related to #30.

**Comment by purejava** [comment]
> It does not anymore. Is this by design?
Yes, the feature was requested with [this](https://bugs.launchpad.net/screenshot-tool/+bug/1665708) bug report and implemented in February with [this](https://github.com/elementary/screenshot-tool/commit/37f600b5f5ee05e047ac660098c641209ccaad6d) commit.
