### ISSUE TITLE
Default to Screenshots subfolder

### ISSUE THREAD

**Issue by cassidyjames** [elementary/screenshot-tool#41]
Camera defaults to a "Webcam" subfolder, and my Pictures folder quickly becomes over-crowded with Screenshots. I wonder if we should default to a ~/Pictures/Screenshots folder.

**Comment by jtvi** [comment]
I took a look about this and had couple of questions.

Should that folder name be translated into the user's current language? And after first time when the folder gets created, we should save that path into user settings?

**Comment by purejava** [comment]
I think the folder name should be translated into the user's current language.

User settings here work as an override for the path coded in the app and therefore should not be modified.
