### ISSUE TITLE
Wrong Save location when using Short-cut

### ISSUE THREAD

**Issue by arshubham** [elementary/screenshot-tool#49]
When taking a screenshot using 'prt sc' shortcut, the screenshot is stored in Pictures folder instead of Screenshots. Taking the screenshot from the application works as expected.

**Comment by purejava** [comment]
This is an issue of gala, not screen-shot-tool.
[This](https://github.com/elementary/gala/tree/new-screenshot-folder) should fix it.

**Comment by J0Ar** [comment]
In the current state (new install and all stable updates) you can define your own custom-shortcut to
(for example) `screenshot-tool --area` and then the pictures are stored in _~/Pictures/Screenshot_
