### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by sugandaaa** [elementary/screenshot-tool#54]
i don't know, where to request feature. so i write to this repository.

please add new feature in this app like Quicktime on mac os, for record screen.

**Comment by btkostner** [comment]
This will probably never be implimented in the screenshot tool because we want to keep it super simple. Fear not though, there is an amazing app called [screencast](https://github.com/artemanufrij/screencast) that does exactly what you need, and it is available on AppCenter!
