### ISSUE TITLE
Build with meson

### ISSUE THREAD

**Issue by awissu** [elementary/screenshot-tool#57]
Hi! I bumped on problem when building rpm in OBS:
```
[   97s] RPM build errors:
[   97s]     Installed (but unpackaged) file(s) found:
[   97s]    /usr/share/locale/ar/LC_MESSAGES/extra.mo
[   97s]    /usr/share/locale/as/LC_MESSAGES/extra.mo
[   97s]    /usr/share/locale/ast/LC_MESSAGES/extra.mo
[   97s]    /usr/share/locale/be/LC_MESSAGES/extra.mo
[   97s]    /usr/share/locale/bg/LC_MESSAGES/extra.mo
[   97s]    /usr/share/locale/bn/LC_MESSAGES/extra.mo
...
```
https://build.opensuse.org/package/live_build_log/home:awissu:branches:X11:Pantheon:Next/screenshot-tool/openSUSE_Tumbleweed/x86_64
These files will conflicts with a file from another package.

**Comment by tintou** [comment]
Please don't include these files in the packaging, they are only made during compilation time, I submitted a patch to meson to not install them but until then you have to ignore them.

**Comment by awissu** [comment]
Fixed in upstream.
