### ISSUE TITLE
Incorrect translation in en_GB.po

### ISSUE THREAD

**Issue by jeremypw** [elementary/screenshot-tool#61]
Polish has been substituted for English:

![screenshot from 2017-10-31 17 03 06](https://user-images.githubusercontent.com/10513844/32237805-daf28228-be5d-11e7-9ff8-f752504907be.png)

**Comment by lewisgoddard** [comment]
Suggestions reviewable at 
1. https://l10n.elementary.io/translate/screenshot-tool/screenshot-tool/en_GB/?checksum=8f0246b952160fba
2. https://l10n.elementary.io/translate/screenshot-tool/screenshot-tool/en_GB/?checksum=8f0246b952160fba

**Comment by danrabbit** [comment]
Closing since it seems Lewis fixed these in Weblate already

**Comment by MaxValue** [comment]
I have sort of a "newbie question": Why do I still have this bug? I have Elementary OS 0.4.1 Loki and update regularly.

**Comment by lewisgoddard** [comment]
Maybe we need to do a translation pull and a release. `po/en_GB.po` doesn't seem to be auto-updating (although it doesn't contain any polish) but `po/extra/en_GB.po` is.
