### ISSUE TITLE
Dark Theme in Screenshot Tool ?  Does not match eOS

### ISSUE THREAD

**Issue by bksubhuti** [elementary/screenshot-tool#62]
My screenshot tool is dark themed.  This should not be like that.  It is inconsistent.
![screenshot from 2017-11-01 20-15-02](https://user-images.githubusercontent.com/18184280/32305195-6c7d131c-bfa2-11e7-8694-3bd464e46a7e.png)

**Comment by btkostner** [comment]
This is by design. The dark theme can be used for utilities.
