### ISSUE TITLE
All screenshots should go in the 'Pictures > Screenshots' folder

### ISSUE THREAD

**Issue by uncertainquark** [elementary/screenshot-tool#71]
Currently
1. Screenshots taken through the "PrtScr" button go in the 'Pictures' folder:
![screenshot from 2018-03-24 15-50-57](https://user-images.githubusercontent.com/22585732/37862948-a272df8a-2f7b-11e8-9e60-5f167841c076.png)

2. While the ones taken through the "Screenshot app" go in the 'Pictures > Screenshots' folder:
![screenshot from 2018-03-24 15-51-01](https://user-images.githubusercontent.com/22585732/37862951-b1db2766-2f7b-11e8-908b-029335386d21.png)

**Comment by cassidyjames** [comment]
This is actually not a bug with the screenshot tool; using the keyboard shortcut actually uses Gala, and there are issues open there for this.

**Comment by uncertainquark** [comment]
Sure, I understand. But it is a bug from the user perspective. The user is left confused with inconsistency in screenshot behavior. If the issue can't be fixed in Gala, the screenshot tool can be made to save screenshots in the Pictures folder for consistency.
