### ISSUE TITLE
Spaces under the lines are different

### ISSUE THREAD

**Issue by ryonakano** [elementary/screenshot-tool#82]
![screenshot from 2018-06-11 21-17-23](https://user-images.githubusercontent.com/26003928/41231332-b8a7b624-6dbd-11e8-9fb4-f37a9a613210.png)

It is very tiny difference, but it seems that the spaces under the lines of "Grab the whole screen" and "Grab the current window" are different.

**Comment by Djaler** [comment]
I can confirm this
